"""Technology-independent public ViewerController protocol."""
from __future__ import annotations

from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Protocol, TypeVar

from .enums import (
    BackgroundTheme,
    ColorScheme,
    MeasurementKind,
    ProjectionType,
    RenderMode,
    SelectionLevel,
    StandardView,
)
from .events import Subscription, ViewerEvent
from .scene import ProjectScene
from .state import (
    CameraState,
    ClippingBox,
    ColorAssignment,
    CompareScene,
    JobHandle,
    PickResult,
    ScenePatch,
    ScreenshotOptions,
    SectionPlane,
    ViewerCapabilities,
    ViewerDisplayPreferences,
    Viewpoint,
)
from .workspace import ViewerWorkspaceState, VisibilitySet, WorkspaceRestoreReport

E = TypeVar("E", bound=ViewerEvent)


class ViewerController(Protocol):
    def capabilities(self) -> ViewerCapabilities: ...
    def load_scene(self, scene: ProjectScene) -> JobHandle: ...
    def update_scene(self, patch: ScenePatch) -> JobHandle: ...
    def clear_scene(self) -> None: ...

    def set_selection(self, ids: Iterable[str], *, mode: str = "replace") -> None: ...
    def get_selection(self) -> tuple[str, ...]: ...
    def set_selection_level(self, level: SelectionLevel) -> None: ...

    def hide(self, ids: Iterable[str]) -> None: ...
    def show(self, ids: Iterable[str]) -> None: ...
    def show_all(self) -> None: ...
    def isolate(self, ids: Iterable[str], *, ghost_context: bool = False) -> None: ...
    def set_transparency(self, ids: Iterable[str], value: float) -> None: ...
    def colorize(self, assignments: Iterable[ColorAssignment]) -> None: ...
    def reset_styles(self, ids: Iterable[str] | None = None) -> None: ...
    def clear_colors(self, ids: Iterable[str] | None = None) -> None: ...
    def clear_transparency(self, ids: Iterable[str] | None = None) -> None: ...
    def get_display_preferences(self) -> ViewerDisplayPreferences: ...
    def set_display_preferences(self, preferences: ViewerDisplayPreferences) -> None: ...
    def set_render_mode(self, mode: RenderMode | None) -> None: ...
    def set_color_scheme(self, scheme: ColorScheme) -> None: ...
    def set_background_theme(self, theme: BackgroundTheme) -> None: ...
    def set_accuracy_mode(self, enabled: bool) -> None: ...

    def get_camera(self) -> CameraState: ...
    def set_camera(self, camera: CameraState, *, animate_ms: int = 0) -> None: ...
    def fit_all(self) -> None: ...
    def fit_selection(self) -> None: ...
    def set_standard_view(self, view: StandardView) -> None: ...
    def set_projection(self, projection: ProjectionType) -> None: ...
    def orbit(self, azimuth_deg: float, elevation_deg: float = 0.0) -> None: ...
    def pan(self, horizontal: float, vertical: float) -> None: ...
    def zoom(self, factor: float) -> None: ...

    def pick_at(self, x: int, y: int, *, mode: str = "replace") -> PickResult | None: ...
    def render(self) -> None: ...
    def resize(self, width: int, height: int) -> None: ...

    def add_section_plane(self, plane: SectionPlane) -> str: ...
    def update_section_plane(self, plane_id: str, plane: SectionPlane) -> None: ...
    def remove_section_plane(self, plane_id: str) -> None: ...
    def set_clipping_box(self, box: ClippingBox | None) -> None: ...

    def begin_measurement(self, kind: MeasurementKind) -> None: ...
    def cancel_tool(self) -> None: ...
    def remove_measurement(self, measurement_id: str) -> None: ...

    def set_compare(self, compare: CompareScene | None) -> JobHandle: ...
    def save_viewpoint(self, name: str, *, owner: str = "") -> Viewpoint: ...
    def list_viewpoints(self) -> tuple[Viewpoint, ...]: ...
    def delete_viewpoint(self, viewpoint_id: str) -> None: ...
    def activate_viewpoint(
        self, viewpoint: Viewpoint, *, allow_scene_mismatch: bool = False
    ) -> None: ...
    def save_visibility_set(self, name: str, *, owner: str = "") -> VisibilitySet: ...
    def list_visibility_sets(self) -> tuple[VisibilitySet, ...]: ...
    def activate_visibility_set(self, visibility_set: VisibilitySet) -> None: ...
    def delete_visibility_set(self, visibility_set_id: str) -> None: ...

    def export_workspace_state(self) -> ViewerWorkspaceState: ...
    def restore_workspace_state(
        self, state: ViewerWorkspaceState, *, allow_scene_mismatch: bool = False
    ) -> WorkspaceRestoreReport: ...
    def save_workspace(self, path: str | Path) -> Path: ...
    def load_workspace(
        self, path: str | Path, *, allow_scene_mismatch: bool = False
    ) -> WorkspaceRestoreReport: ...

    def screenshot(self, options: ScreenshotOptions) -> bytes: ...
    def screenshot_to_file(
        self, path: str | Path, options: ScreenshotOptions | None = None
    ) -> Path: ...
    def subscribe(self, event_type: type[E], handler: Callable[[E], None]) -> Subscription: ...
    def shutdown(self) -> None: ...


__all__ = ["ViewerController"]
