"""Backward-compatible product constants for legacy root modules.

New code imports :mod:`cws_convertor.product`; the historical root modules may
keep importing names from this facade during the architecture migration.
"""
from cws_convertor.product import (  # noqa: F401
    APP_DESCRIPTION,
    APP_NAME,
    APP_PUBLISHER,
    APP_SHORT_NAME,
    APP_SLUG,
    APP_VERSION,
    APP_VERSION_NUMERIC,
    CLI_EXE_NAME,
    DEFAULT_OUTPUT_FOLDER,
    DEFAULT_PROJECT_FOLDER,
    DISTRIBUTION_DIRECTORY,
    GUI_EXE_NAME,
    INSTALLER_BASENAME,
    LEGACY_APP_NAME,
    LEGACY_PAYLOAD_MARKER,
    PORTABLE_BASENAME,
    PROJECT_FILE_EXTENSION,
    PROJECT_PACKAGE_FORMAT,
    PROJECT_SCHEMA_VERSION,
    PROJECT_STORAGE_VERSION,
    TRUSTED_PDF_FORMAT,
    USER_AGENT,
)

PRODUCT_NAME = APP_NAME
PRODUCT_SHORT_NAME = APP_SHORT_NAME
PRODUCT_SLUG = APP_SLUG
PUBLISHER = APP_PUBLISHER
DESCRIPTION = APP_DESCRIPTION
VERSION = APP_VERSION
SEMVER = APP_VERSION
WINDOWS_FILE_VERSION = APP_VERSION_NUMERIC
PROJECT_EXTENSION = PROJECT_FILE_EXTENSION
GUI_EXECUTABLE = GUI_EXE_NAME
CLI_EXECUTABLE = CLI_EXE_NAME
DEFAULT_OUTPUT_DIRECTORY = DEFAULT_OUTPUT_FOLDER
DEFAULT_PROJECT_DIRECTORY = DEFAULT_PROJECT_FOLDER
LEGACY_PAYLOAD_FAMILY = LEGACY_PAYLOAD_MARKER
