"""Native project intake -> stored project -> existing isolated batch route."""
from __future__ import annotations
from contextlib import redirect_stdout
from dataclasses import asdict
from io import StringIO
from pathlib import Path
from types import SimpleNamespace
import json
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
import cadquery as cq
from cws_convertor.project import ProjectSession
from cws_convertor.manufacturing_interpreter.batch_cli import run_batch


class ProjectBatchScopeTests(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory(); self.addCleanup(self.temp.cleanup)
        self.root=Path(self.temp.name);self.path=self.root/'two_bodies.step'
        # Independent dimensions and placements, not generated by recognition.
        cq.exporters.export(cq.Compound.makeCompound([
            cq.Solid.makeBox(20,30,100),cq.Solid.makeBox(10,20,200).translate((100,0,0))]),str(self.path))
        self.session=ProjectSession.new('Source-body scope');self.addCleanup(self.session.close)
        self.source_id=self.session.register_sources([self.path],include_step_geometry=False)[0].source.source_id
        self.session.semantic_import_source(self.source_id)
        self.assertEqual(2,len(self.session.project.parts))

    def test_stored_multipart_source_runs_each_exact_selector(self):
        package=self.session.save(self.root/'source.cwscproj')
        output=self.root/'proof'; aggregate=self.root/'aggregate.json'
        args=SimpleNamespace(project=str(package),parts=(),output=str(output),json_report=str(aggregate),
                             timeout=60.0,benchmark=False,inputs=())
        with redirect_stdout(StringIO()):run_batch(args)
        report=json.loads(aggregate.read_text())
        self.assertEqual(2,len(report['results']))
        self.assertTrue(all('output' in r for r in report['results']),report['results'])
        details=[json.loads(Path(r['output']).read_text()) for r in report['results']]
        self.assertEqual(set(self.session.project.parts),{r['part_id'] for r in details})
        self.assertEqual([40000,60000],sorted(round(r['body_inventory']['sum_solid_volume_mm3']) for r in details))
        self.assertTrue(all(r['material_evidence']['status']=='UNRESOLVED' for r in details))
        self.assertTrue(all(r['readiness']!='READY' for r in details))

    def test_worker_cannot_relabel_a_verified_project_selector(self):
        from cws_convertor.manufacturing_interpreter.isolated import _worker
        part=next(iter(self.session.project.parts.values()))
        source=self.session.project.sources[self.source_id]
        outputs=[]
        options=dict(source_part=part.base_to_dict(),source_record=asdict(source),
                     part_id='wrong-occurrence',source_sha256=source.sha256)
        _worker(str(self.path),options,SimpleNamespace(put=outputs.append))
        self.assertEqual('FAILED',outputs[0][0])
        self.assertIn('part_id',str(outputs[0][1]))

if __name__=='__main__':unittest.main(verbosity=2)
