"""Manufacturing planning primitives for CWS Convertor."""
from .faces_model import (
    MANUFACTURING_FACE_SCHEMA,
    MANUFACTURING_FACE_ALGORITHM,
    FaceLocalFrame,
    FaceProofStatus,
    FaceResolutionReport,
    ManufacturingFace,
    ManufacturingFaceRole,
    SurfaceType,
)
from .faces import (
    DstvFaceMappingAdapter,
    ManufacturingFaceResolver,
    ManufacturingFaceService,
    ManufacturingFaceValidator,
)
from .contact_model import (
    CONTACT_PATCH_SCHEMA,
    CONTACT_ALGORITHM,
    ContactPatch,
    ContactRelationType,
    ContactResolutionReport,
)
from .contact import (
    ExactContactGeometryEngine,
    ContactPatchValidator,
    ContactGeometryService,
)
from .marking_model import (
    MARK_FEATURE_SCHEMA,
    MARK_SET_SCHEMA,
    MARKING_ALGORITHM,
    ExclusionKind,
    MarkExclusionZone,
    MarkFeature,
    MarkKind,
    MarkSegment2D,
    MarkSet,
    MarkStatus,
    MarkingRuleSet,
)
from .marking import ContactScribingEngine, MarkSetValidator
from .identification_model import (
    IDENTIFICATION_SCHEMA,
    IDENTIFICATION_SET_SCHEMA,
    IDENTIFICATION_ALGORITHM,
    HoleReferenceInput,
    HoleReferenceMark,
    IdentificationRuleSet,
    IdentificationSet,
    IdentificationStatus,
    IdentificationTextIntent,
    IdentificationTextRequest,
    ReadabilityPolicy,
)
from .identification import IdentificationPlanner
from .machine_capability_model import (
    MACHINE_CAPABILITY_SCHEMA,
    MACHINE_CAPABILITY_ALGORITHM,
    CapabilityStatus,
    MachineCapabilityReport,
    MachineFeatureDecision,
    MachineFeatureType,
)
from .machine_capability import MachineCapabilityEvaluator
from .nesting_binding_model import (
    NESTING_PLACEMENT_SCHEMA,
    NESTED_FEATURE_SCHEMA,
    NESTING_MARKING_SCHEMA,
    NESTING_BINDING_ALGORITHM,
    CommonCutZone,
    NestedFeatureKind,
    NestedFeatureStatus,
    NestedManufacturingFeature,
    NestingMarkingReport,
    NestingPlacement,
    StockClampZone,
)
from .nesting_binding import NestingMarkBinder
from .nesting_validation import IndependentNestingMarkValidator, NestingValidationResult

__all__ = [
    "MANUFACTURING_FACE_SCHEMA",
    "MANUFACTURING_FACE_ALGORITHM",
    "FaceLocalFrame",
    "FaceProofStatus",
    "FaceResolutionReport",
    "ManufacturingFace",
    "ManufacturingFaceRole",
    "SurfaceType",
    "DstvFaceMappingAdapter",
    "ManufacturingFaceResolver",
    "ManufacturingFaceService",
    "ManufacturingFaceValidator",
    "CONTACT_PATCH_SCHEMA",
    "CONTACT_ALGORITHM",
    "ContactPatch",
    "ContactRelationType",
    "ContactResolutionReport",
    "ExactContactGeometryEngine",
    "ContactPatchValidator",
    "ContactGeometryService",
    "MARK_FEATURE_SCHEMA",
    "MARK_SET_SCHEMA",
    "MARKING_ALGORITHM",
    "ExclusionKind",
    "MarkExclusionZone",
    "MarkFeature",
    "MarkKind",
    "MarkSegment2D",
    "MarkSet",
    "MarkStatus",
    "MarkingRuleSet",
    "ContactScribingEngine",
    "MarkSetValidator",
    "IDENTIFICATION_SCHEMA",
    "IDENTIFICATION_SET_SCHEMA",
    "IDENTIFICATION_ALGORITHM",
    "HoleReferenceInput",
    "HoleReferenceMark",
    "IdentificationRuleSet",
    "IdentificationSet",
    "IdentificationStatus",
    "IdentificationTextIntent",
    "IdentificationTextRequest",
    "ReadabilityPolicy",
    "IdentificationPlanner",
    "MACHINE_CAPABILITY_SCHEMA",
    "MACHINE_CAPABILITY_ALGORITHM",
    "CapabilityStatus",
    "MachineCapabilityReport",
    "MachineFeatureDecision",
    "MachineFeatureType",
    "MachineCapabilityEvaluator",
    "NESTING_PLACEMENT_SCHEMA",
    "NESTED_FEATURE_SCHEMA",
    "NESTING_MARKING_SCHEMA",
    "NESTING_BINDING_ALGORITHM",
    "CommonCutZone",
    "NestedFeatureKind",
    "NestedFeatureStatus",
    "NestedManufacturingFeature",
    "NestingMarkingReport",
    "NestingPlacement",
    "StockClampZone",
    "NestingMarkBinder",
    "IndependentNestingMarkValidator",
    "NestingValidationResult",
]
