"""Public Viewer Core protocol; renderer implementations live behind it."""
from __future__ import annotations

from collections.abc import Callable, Iterable
from typing import Any, Protocol, TypeVar

from cws_viewer.contracts.camera import CameraState, ProjectionType, ScreenshotOptions, StandardView
from cws_viewer.contracts.compare import CompareScene
from cws_viewer.contracts.measurement import MeasurementKind
from cws_viewer.contracts.scene import ColorAssignment, ProjectScene, ScenePatch
from cws_viewer.contracts.section import ClippingBox, SectionPlane
from cws_viewer.contracts.selection import SelectionLevel
from cws_viewer.contracts.viewpoint import Viewpoint
from .capabilities import ViewerCapabilities

T = TypeVar("T")


class JobHandle(Protocol[T]):
    @property
    def job_id(self) -> str: ...

    def cancel(self) -> None: ...

    def done(self) -> bool: ...

    def result(self, timeout: float | None = None) -> T: ...


class Subscription(Protocol):
    def close(self) -> None: ...


class ViewerController(Protocol):
    def capabilities(self) -> ViewerCapabilities: ...

    def load_scene(self, scene: ProjectScene) -> JobHandle[None]: ...

    def update_scene(self, patch: ScenePatch) -> JobHandle[None]: ...

    def clear_scene(self) -> None: ...

    def set_selection(self, ids: Iterable[str], *, mode: str = "replace") -> None: ...

    def get_selection(self) -> tuple[str, ...]: ...

    def set_selection_level(self, level: SelectionLevel) -> None: ...

    def hide(self, ids: Iterable[str]) -> None: ...

    def show(self, ids: Iterable[str]) -> None: ...

    def show_all(self) -> None: ...

    def isolate(self, ids: Iterable[str], *, ghost_context: bool = False) -> None: ...

    def set_transparency(self, ids: Iterable[str], value: float) -> None: ...

    def colorize(self, assignments: Iterable[ColorAssignment]) -> None: ...

    def reset_styles(self, ids: Iterable[str] | None = None) -> None: ...

    def get_camera(self) -> CameraState: ...

    def set_camera(self, camera: CameraState, *, animate_ms: int = 0) -> None: ...

    def fit_all(self) -> None: ...

    def fit_selection(self) -> None: ...

    def set_standard_view(self, view: StandardView) -> None: ...

    def set_projection(self, projection: ProjectionType) -> None: ...

    def add_section_plane(self, plane: SectionPlane) -> str: ...

    def update_section_plane(self, plane_id: str, plane: SectionPlane) -> None: ...

    def remove_section_plane(self, plane_id: str) -> None: ...

    def set_clipping_box(self, box: ClippingBox | None) -> None: ...

    def begin_measurement(self, kind: MeasurementKind) -> None: ...

    def cancel_tool(self) -> None: ...

    def remove_measurement(self, measurement_id: str) -> None: ...

    def set_compare(self, compare: CompareScene | None) -> JobHandle[None]: ...

    def save_viewpoint(self, name: str) -> Viewpoint: ...

    def activate_viewpoint(self, viewpoint: Viewpoint) -> None: ...

    def screenshot(self, options: ScreenshotOptions) -> bytes: ...

    def subscribe(self, event_type: type[T], handler: Callable[[T], Any]) -> Subscription: ...

    def shutdown(self) -> None: ...


__all__ = ["JobHandle", "Subscription", "ViewerController"]
