from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

from cws_viewer.core.loader_v2_probe import run_probe


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "validation" / "loader_engine_v2"


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Loader Engine V2 source and packaged evidence")
    parser.add_argument("--runtime-dir", type=Path)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    source_path = output_dir / "SOURCE_RUNTIME_PROBE.json"
    packaged_path = output_dir / "PACKAGED_RUNTIME_PROBE.json"
    source = run_probe(source_path, require_frozen=False)

    packaged: dict[str, Any] | None = None
    packaged_command: list[str] | None = None
    if args.runtime_dir:
        executable = args.runtime_dir.resolve() / "CWS_Convertor_CLI.exe"
        packaged_command = [str(executable), "loader-engine-v2-probe", "--output", str(packaged_path)]
        completed = subprocess.run(packaged_command, cwd=args.runtime_dir.resolve(), check=False)
        if completed.returncode == 0 and packaged_path.exists():
            packaged = _read_json(packaged_path)

    gates = {
        "source_probe": source.get("status") == "PASS",
        "packaged_probe_present": packaged is not None,
        "packaged_probe_pass": packaged is not None and packaged.get("status") == "PASS",
        "packaged_frozen_runtime": packaged is not None and packaged.get("packaged") is True,
        "persistent_parallel_worker_pool": packaged is not None and packaged.get("gates", {}).get("parallel_speedup") is True,
        "seven_band_viewport_priority": packaged is not None and packaged.get("gates", {}).get("viewport_priority_order") is True,
        "memory_mapped_cache_v2": packaged is not None and packaged.get("gates", {}).get("cache_v2_mmap") is True,
        "bounded_scene_upload": packaged is not None and packaged.get("gates", {}).get("bounded_scene_upload") is True,
    }
    passed = sum(bool(value) for value in gates.values())
    status = "COMPLETE" if passed == len(gates) else "NOT_PROVEN"
    acceptance = {
        "schema": "cws.loader-engine-v2.acceptance.v1",
        "status": status,
        "scope": "worker pool, viewport priority, Cache V2, bounded scene upload and packaged performance evidence",
        "source_probe": str(source_path),
        "packaged_probe": str(packaged_path) if packaged is not None else None,
        "packaged_command": packaged_command,
        "gates": gates,
        "summary": {"passed": passed, "total": len(gates)},
        "notes": [
            "Measurements are generated by the source runtime and the frozen one-folder CLI executable.",
            "Trimble visual parity is outside this Loader Engine V2 performance gate.",
        ],
    }
    acceptance_path = output_dir / "LOADER_ENGINE_V2_ACCEPTANCE.json"
    acceptance_path.write_text(json.dumps(acceptance, indent=2, ensure_ascii=True), encoding="utf-8")
    markdown = [
        "# Loader Engine V2 acceptance",
        "",
        f"Status: **{status}**",
        f"Gates: **{passed}/{len(gates)}**",
        "",
        "| Gate | Result |",
        "|---|---|",
    ]
    markdown.extend(f"| {name} | {'PASS' if value else 'NOT PROVEN'} |" for name, value in gates.items())
    markdown.extend(["", "The packaged probe must execute from `CWS_Convertor_CLI.exe`; source-only evidence cannot close this gate."])
    (output_dir / "LOADER_ENGINE_V2_ACCEPTANCE.md").write_text("\n".join(markdown) + "\n", encoding="utf-8")
    print(f"LOADER_ENGINE_V2 = {passed}/{len(gates)} {status}")
    return 0 if status == "COMPLETE" else 1


if __name__ == "__main__":
    raise SystemExit(main())
