"""One exact-source software-beta promotion barrier, not product qualification."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

REQUIRED_JOBS = {'core', 'broad', 'installer'}


def validate_corpus(corpus, expected_sha):
    """Recompute the corpus policy and confusion counts; do not trust PASS alone."""
    from cws_convertor.manufacturing_interpreter.acceptance_policy import corpus_verdict
    if not isinstance(corpus, dict):
        return ['RECOGNITION_CORPUS_MISSING']
    summary, rows = corpus.get('summary', {}), corpus.get('categories', [])
    if not isinstance(summary, dict) or not isinstance(rows, list) or not all(isinstance(r, dict) for r in rows):
        return ['RECOGNITION_CORPUS_INVALID']
    problems = []
    if (summary.get('source_commit') != expected_sha or summary.get('source_unchanged') is not True
            or summary.get('schema') != 'cws-mgi-v3-acceptance-corpus-v2'):
        problems.append('RECOGNITION_CORPUS_SOURCE_MISMATCH')
    identifiers = [row.get('id') for row in rows]
    if (len(rows) != 45 or set(identifiers) != {f'{i:02d}' for i in range(1, 46)}
            or summary.get('category_count') != 45 or summary.get('generated_step_count') != 45
            or not all(row.get('deterministic_identity') is True for row in rows)):
        problems.append('RECOGNITION_CORPUS_INCOMPLETE')
    counts = [0, 0, 0]
    for row in rows:
        if row.get('features_scored') is True:
            truth, features = row.get('truth'), row.get('features')
            if (not isinstance(truth, list) or not isinstance(features, list)
                    or not all(isinstance(v, str) for v in truth + features)):
                problems.append('RECOGNITION_CORPUS_INVALID_LABELS'); continue
            truth, features = set(truth), set(features)
            counts = [counts[0] + len(truth & features), counts[1] + len(features - truth),
                      counts[2] + len(truth - features)]
        if row.get('production_readiness') == 'READY':
            problems.append('RECOGNITION_CORPUS_UNSUPPORTED_MACHINE_APPROVAL')
    tp, fp, fn = counts
    precision, recall = round(tp / max(1, tp + fp), 6), round(tp / max(1, tp + fn), 6)
    if (counts != [summary.get(k) for k in ('true_positive', 'false_positive', 'false_negative')]
            or precision != summary.get('precision') or recall != summary.get('recall')
            or sum(row.get('unsafe_ready') is not False for row in rows) != summary.get('false_ready')):
        problems.append('RECOGNITION_CORPUS_COUNTS_MISMATCH')
    verdict = corpus_verdict(summary, rows=rows)
    if summary.get('pass') is not True or not verdict['passed']:
        problems.append('RECOGNITION_USEFULNESS_NOT_ACCEPTED')
    return list(dict.fromkeys(problems))


def validate_promotion(job_results, expected_sha, installer, strict, broad, corpus=None):
    problems=[]
    if set(job_results) != REQUIRED_JOBS or any(v != 'success' for v in job_results.values()):
        problems.append('REQUIRED_JOB_NOT_SUCCESSFUL')
    if len(expected_sha) != 40 or any(c not in '0123456789abcdef' for c in expected_sha):
        problems.append('INVALID_SOURCE_SHA')
    if installer.get('source_commit') != expected_sha or installer.get('status') != 'PASS' or installer.get('source_unchanged') is not True:
        problems.append('INSTALLER_SOURCE_OR_STATUS_MISMATCH')
    if installer.get('full_product_release_approved') is not False or installer.get('direct_machine_transfer') is not False:
        problems.append('UNSUPPORTED_PRODUCTION_APPROVAL')
    plate=installer.get('installed_plate_integration',{})
    if plate.get('status') != 'PASS' or plate.get('checks',0)<20 or plate.get('python_on_child_path') is not False:
        problems.append('INSTALLED_PLATE_PROOF_MISSING')
    native = installer.get('installed_recognition_integration', {})
    if (native.get('status') != 'PASS' or type(native.get('checks')) is not int
            or native.get('checks', 0) < 50 or native.get('python_on_child_path') is not False
            or native.get('source_commit') != expected_sha
            or not isinstance(native.get('executable_sha256'), str)
            or len(native.get('executable_sha256', '')) != 64):
        problems.append('INSTALLED_RECOGNITION_PROOF_MISSING_OR_STALE')
    problems.extend(validate_corpus(corpus, expected_sha))
    summary=strict.get('summary',strict)
    # Check the actual count generated by the manifest, never a fixed optimistic total.
    if (strict.get('status')!='PASS' or summary.get('required_suites',0)<=0 or
            summary.get('passed_suites')!=summary.get('required_suites') or
            summary.get('tests_run',0)<=0 or summary.get('tests_passed')!=summary.get('tests_run') or
            summary.get('skipped_events')!=0):
        problems.append('STRICT_SUITE_INCOMPLETE')
    if len(broad)!=4:
        problems.append('BROAD_SHARD_MISSING')
    return problems


def main():
    parser=argparse.ArgumentParser();parser.add_argument('--root',type=Path,required=True)
    parser.add_argument('--sha',required=True);parser.add_argument('--jobs',required=True)
    args=parser.parse_args();root=args.root
    installers=list(root.rglob('INSTALLER_ACCEPTANCE.json'))
    finals=list(root.rglob('FINAL_ACCEPTANCE.json'))
    if len(installers)!=1 or len(finals)!=1:
        raise RuntimeError('Exactly one installer and strict acceptance manifest are required')
    installer=json.loads(installers[0].read_text(encoding='utf-8-sig'))
    strict=json.loads(finals[0].read_text(encoding='utf-8-sig'))
    # Broad-job success is a required independent GitHub matrix result; retain
    # the complete shard artifacts as evidence, including all declared skips.
    broad_dirs=sorted(p for p in root.iterdir() if p.is_dir() and p.name.startswith('CWS_Installer_Regression_'))
    corpora = list(root.rglob('CORPUS_MANIFEST.json'))
    if len(corpora) != 1:
        raise RuntimeError('Exactly one source-bound recognition corpus is required')
    corpus = json.loads(corpora[0].read_text(encoding='utf-8-sig'))
    problems=validate_promotion(json.loads(args.jobs),args.sha,installer,strict,broad_dirs,corpus)
    candidates=list(root.rglob(installer.get('installer','__missing_installer__')))
    if len(candidates)!=1:problems.append('INSTALLER_FILE_NOT_UNIQUE')
    else:
        with candidates[0].open('rb') as f:observed=hashlib.file_digest(f,'sha256').hexdigest()
        if observed!=installer.get('installer_sha256'):problems.append('INSTALLER_HASH_MISMATCH')
    # Recognition evidence binds its own source; fail when absent or different.
    source=strict.get('source',{})
    bound=source.get('git_sha') or source.get('commit') or source.get('head_sha') or source.get('head') or strict.get('source_commit')
    if (bound!=args.sha or source.get('dirty') is not False or strict.get('source_unchanged_during_run') is not True):problems.append('STRICT_SOURCE_SHA_MISMATCH')
    v3 = installer.get('installed_pdf_v3_integration', {})
    if (v3.get('status') != 'PASS' or v3.get('source_commit') != args.sha
            or v3.get('checks', 0) < 40 or v3.get('python_on_child_path') is not False):
        problems.append('INSTALLED_PDF_V3_PROOF_MISSING_OR_STALE')
    if problems:raise RuntimeError('; '.join(problems))
    out=root/'promoted';out.mkdir(exist_ok=True)
    import shutil
    shutil.copy2(candidates[0],out/candidates[0].name)
    shutil.copy2(installers[0],out/'INSTALLER_ACCEPTANCE.json')
    shutil.copy2(corpora[0],out/'CORPUS_MANIFEST.json')
    (out/'SHA256SUMS.txt').write_text(installer['installer_sha256']+'  '+candidates[0].name+'\n',encoding='utf-8')
    payload={'schema':'cws-integrated-beta-promotion-2','source_commit':args.sha,'status':'PASS',
             'required_jobs':json.loads(args.jobs),'installer_sha256':installer['installer_sha256'],
             'full_product_release_approved':False,'machine_transfer_authorized':False,
             'scope':'software beta; remaining audit/hardware/recognition limitations are not waived',
             'recognition_summary':corpus['summary'], 'strict_summary':strict.get('summary',strict),'shards': [p.name for p in broad_dirs]}
    (out/'PROMOTION.json').write_text(json.dumps(payload,indent=2),encoding='utf-8')
    print(json.dumps({'status':'PASS','installer':candidates[0].name,'source_commit':args.sha}))

if __name__=='__main__':main()
