"""Stable machine-readable profile nesting issue codes."""

NESTING_ERROR_CODES = {
    "CWS-NEST-001": "ontbrekende/ongeldige productielengte",
    "CWS-NEST-002": "profiel of section identity ontbreekt",
    "CWS-NEST-003": "materiaal/kwaliteit ontbreekt",
    "CWS-NEST-004": "manufacturing hash stale/mismatch",
    "CWS-NEST-005": "unsupported part type",
    "CWS-NEST-006": "start/eindcut niet eenduidig",
    "CWS-NEST-007": "ongeldige productieassen/referentiezijde",
    "CWS-NEST-008": "geen geschikte machine",
    "CWS-NEST-009": "zaaghoek buiten bereik",
    "CWS-NEST-010": "vereist gereedschap ontbreekt",
    "CWS-NEST-011": "stuk past in geen enkele stockoptie",
    "CWS-NEST-012": "stock quantity tekort",
    "CWS-NEST-013": "materiaal-/grade-/heatconflict",
    "CWS-NEST-014": "fysieke overlap",
    "CWS-NEST-015": "stockgrensoverschrijding",
    "CWS-NEST-016": "klem-/veiligheidszone geschonden",
    "CWS-NEST-017": "ongeldige common cut",
    "CWS-NEST-018": "materiaalbalans mismatch",
    "CWS-NEST-019": "ontbrekende stukinstantie of duplicate assignment",
    "CWS-NEST-020": "solver timeout zonder geldige oplossing",
    "CWS-NEST-021": "solverresultaat faalt onafhankelijke validatie",
    "CWS-NEST-022": "plan stale door projectwijziging",
    "CWS-NEST-023": "plan stale door machine/tool/formulewijziging",
    "CWS-NEST-024": "plan stale door stockwijziging",
    "CWS-NEST-025": "stock/reserveringsconflict",
    "CWS-NEST-026": "unsupported compound cut",
    "CWS-NEST-027": "handmatige lock maakt probleem infeasible",
    "CWS-NEST-028": "projectmigratie of schema incompatibel",
    "CWS-NEST-029": "outputartefact/write/checksumfout",
    "CWS-NEST-030": "niet-gevalideerde propriëtaire adapter",
}
